/*
* generated by Xtext
*/
package org.xtext.example.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cSurveysAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cSurveysSurveyParserRuleCall_1_0_0 = (RuleCall)cSurveysAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cQuestionMarkQuestionMarkQuestionMarkQuestionMarkQuestionMarkQuestionMarkKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cSurveysAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cSurveysSurveyParserRuleCall_1_1_1_0 = (RuleCall)cSurveysAssignment_1_1_1.eContents().get(0);
		
		//Model:
		//	{Model} (surveys+=Survey ("??????" surveys+=Survey)*)?;
		public ParserRule getRule() { return rule; }

		//{Model} (surveys+=Survey ("??????" surveys+=Survey)*)?
		public Group getGroup() { return cGroup; }

		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }

		//(surveys+=Survey ("??????" surveys+=Survey)*)?
		public Group getGroup_1() { return cGroup_1; }

		//surveys+=Survey
		public Assignment getSurveysAssignment_1_0() { return cSurveysAssignment_1_0; }

		//Survey
		public RuleCall getSurveysSurveyParserRuleCall_1_0_0() { return cSurveysSurveyParserRuleCall_1_0_0; }

		//("??????" surveys+=Survey)*
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"??????"
		public Keyword getQuestionMarkQuestionMarkQuestionMarkQuestionMarkQuestionMarkQuestionMarkKeyword_1_1_0() { return cQuestionMarkQuestionMarkQuestionMarkQuestionMarkQuestionMarkQuestionMarkKeyword_1_1_0; }

		//surveys+=Survey
		public Assignment getSurveysAssignment_1_1_1() { return cSurveysAssignment_1_1_1; }

		//Survey
		public RuleCall getSurveysSurveyParserRuleCall_1_1_1_0() { return cSurveysSurveyParserRuleCall_1_1_1_0; }
	}

	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Question");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMultipleChoiceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOpenParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRating_ImplParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cRankingParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDichotomousParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cSumConstantParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cStapleParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Question:
		//	MultipleChoice | Open | Rating_Impl | Ranking | Dichotomous | SumConstant | Staple;
		public ParserRule getRule() { return rule; }

		//MultipleChoice | Open | Rating_Impl | Ranking | Dichotomous | SumConstant | Staple
		public Alternatives getAlternatives() { return cAlternatives; }

		//MultipleChoice
		public RuleCall getMultipleChoiceParserRuleCall_0() { return cMultipleChoiceParserRuleCall_0; }

		//Open
		public RuleCall getOpenParserRuleCall_1() { return cOpenParserRuleCall_1; }

		//Rating_Impl
		public RuleCall getRating_ImplParserRuleCall_2() { return cRating_ImplParserRuleCall_2; }

		//Ranking
		public RuleCall getRankingParserRuleCall_3() { return cRankingParserRuleCall_3; }

		//Dichotomous
		public RuleCall getDichotomousParserRuleCall_4() { return cDichotomousParserRuleCall_4; }

		//SumConstant
		public RuleCall getSumConstantParserRuleCall_5() { return cSumConstantParserRuleCall_5; }

		//Staple
		public RuleCall getStapleParserRuleCall_6() { return cStapleParserRuleCall_6; }
	}

	public class SurveyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Survey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSurveyAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cQuestionsAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cQuestionsQuestionParserRuleCall_2_0_0 = (RuleCall)cQuestionsAssignment_2_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Assignment cQuestionsAssignment_2_2_0 = (Assignment)cGroup_2_2.eContents().get(0);
		private final RuleCall cQuestionsQuestionParserRuleCall_2_2_0_0 = (RuleCall)cQuestionsAssignment_2_2_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2_1 = (Keyword)cGroup_2_2.eContents().get(1);
		
		//Survey:
		//	{Survey} name=EString (questions+=Question ";" (questions+=Question ";")*)?;
		public ParserRule getRule() { return rule; }

		//{Survey} name=EString (questions+=Question ";" (questions+=Question ";")*)?
		public Group getGroup() { return cGroup; }

		//{Survey}
		public Action getSurveyAction_0() { return cSurveyAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//(questions+=Question ";" (questions+=Question ";")*)?
		public Group getGroup_2() { return cGroup_2; }

		//questions+=Question
		public Assignment getQuestionsAssignment_2_0() { return cQuestionsAssignment_2_0; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_2_0_0() { return cQuestionsQuestionParserRuleCall_2_0_0; }

		//";"
		public Keyword getSemicolonKeyword_2_1() { return cSemicolonKeyword_2_1; }

		//(questions+=Question ";")*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//questions+=Question
		public Assignment getQuestionsAssignment_2_2_0() { return cQuestionsAssignment_2_2_0; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_2_2_0_0() { return cQuestionsQuestionParserRuleCall_2_2_0_0; }

		//";"
		public Keyword getSemicolonKeyword_2_2_1() { return cSemicolonKeyword_2_2_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class MultipleChoiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultipleChoice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMultipleChoiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMultipleChoiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTheKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cUserKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Keyword cMayKeyword_5_0 = (Keyword)cAlternatives_5.eContents().get(0);
		private final Assignment cIsRequiredAssignment_5_1 = (Assignment)cAlternatives_5.eContents().get(1);
		private final Keyword cIsRequiredIsRequiredKeyword_5_1_0 = (Keyword)cIsRequiredAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cAnswerKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cQuestionAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cQuestionEStringParserRuleCall_6_2_0 = (RuleCall)cQuestionAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cWithKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Alternatives cAlternatives_7_1 = (Alternatives)cGroup_7.eContents().get(1);
		private final Keyword cOneOfKeyword_7_1_0 = (Keyword)cAlternatives_7_1.eContents().get(0);
		private final Keyword cSomeOfKeyword_7_1_1 = (Keyword)cAlternatives_7_1.eContents().get(1);
		private final Keyword cTheseKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Assignment cChoiceAssignment_7_3 = (Assignment)cGroup_7.eContents().get(3);
		private final RuleCall cChoiceChoiceParserRuleCall_7_3_0 = (RuleCall)cChoiceAssignment_7_3.eContents().get(0);
		private final Group cGroup_7_4 = (Group)cGroup_7.eContents().get(4);
		private final Keyword cCommaKeyword_7_4_0 = (Keyword)cGroup_7_4.eContents().get(0);
		private final Assignment cChoiceAssignment_7_4_1 = (Assignment)cGroup_7_4.eContents().get(1);
		private final RuleCall cChoiceChoiceParserRuleCall_7_4_1_0 = (RuleCall)cChoiceAssignment_7_4_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cOrKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cWithKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cSomethingKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Keyword cElseKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Assignment cOtherAssignment_8_4 = (Assignment)cGroup_8.eContents().get(4);
		private final RuleCall cOtherEStringParserRuleCall_8_4_0 = (RuleCall)cOtherAssignment_8_4.eContents().get(0);
		private final Keyword cFullStopKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Assignment cForkAssignment_10_0 = (Assignment)cGroup_10.eContents().get(0);
		private final RuleCall cForkChoiceForkParserRuleCall_10_0_0 = (RuleCall)cForkAssignment_10_0.eContents().get(0);
		private final Group cGroup_10_1 = (Group)cGroup_10.eContents().get(1);
		private final Keyword cCommaKeyword_10_1_0 = (Keyword)cGroup_10_1.eContents().get(0);
		private final Assignment cForkAssignment_10_1_1 = (Assignment)cGroup_10_1.eContents().get(1);
		private final RuleCall cForkChoiceForkParserRuleCall_10_1_1_0 = (RuleCall)cForkAssignment_10_1_1.eContents().get(0);
		
		//MultipleChoice:
		//	{MultipleChoice} "MultipleChoice" name=ID ":" ("The"? "user")? ("may" | isRequired?="is required")? ("to"? "answer"?
		//	question=EString)? ("with"? ("one of" | "some of")? "these:"? choice+=Choice ("," choice+=Choice)*)? ("or" "with"?
		//	"something"? "else"? other=EString)? "."? (Fork+=ChoiceFork ("," Fork+=ChoiceFork)*)?;
		public ParserRule getRule() { return rule; }

		//{MultipleChoice} "MultipleChoice" name=ID ":" ("The"? "user")? ("may" | isRequired?="is required")? ("to"? "answer"?
		//question=EString)? ("with"? ("one of" | "some of")? "these:"? choice+=Choice ("," choice+=Choice)*)? ("or" "with"?
		//"something"? "else"? other=EString)? "."? (Fork+=ChoiceFork ("," Fork+=ChoiceFork)*)?
		public Group getGroup() { return cGroup; }

		//{MultipleChoice}
		public Action getMultipleChoiceAction_0() { return cMultipleChoiceAction_0; }

		//"MultipleChoice"
		public Keyword getMultipleChoiceKeyword_1() { return cMultipleChoiceKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("The"? "user")?
		public Group getGroup_4() { return cGroup_4; }

		//"The"?
		public Keyword getTheKeyword_4_0() { return cTheKeyword_4_0; }

		//"user"
		public Keyword getUserKeyword_4_1() { return cUserKeyword_4_1; }

		//("may" | isRequired?="is required")?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }

		//"may"
		public Keyword getMayKeyword_5_0() { return cMayKeyword_5_0; }

		//isRequired?="is required"
		public Assignment getIsRequiredAssignment_5_1() { return cIsRequiredAssignment_5_1; }

		//"is required"
		public Keyword getIsRequiredIsRequiredKeyword_5_1_0() { return cIsRequiredIsRequiredKeyword_5_1_0; }

		//("to"? "answer"? question=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"to"?
		public Keyword getToKeyword_6_0() { return cToKeyword_6_0; }

		//"answer"?
		public Keyword getAnswerKeyword_6_1() { return cAnswerKeyword_6_1; }

		//question=EString
		public Assignment getQuestionAssignment_6_2() { return cQuestionAssignment_6_2; }

		//EString
		public RuleCall getQuestionEStringParserRuleCall_6_2_0() { return cQuestionEStringParserRuleCall_6_2_0; }

		//("with"? ("one of" | "some of")? "these:"? choice+=Choice ("," choice+=Choice)*)?
		public Group getGroup_7() { return cGroup_7; }

		//"with"?
		public Keyword getWithKeyword_7_0() { return cWithKeyword_7_0; }

		//("one of" | "some of")?
		public Alternatives getAlternatives_7_1() { return cAlternatives_7_1; }

		//"one of"
		public Keyword getOneOfKeyword_7_1_0() { return cOneOfKeyword_7_1_0; }

		//"some of"
		public Keyword getSomeOfKeyword_7_1_1() { return cSomeOfKeyword_7_1_1; }

		//"these:"?
		public Keyword getTheseKeyword_7_2() { return cTheseKeyword_7_2; }

		//choice+=Choice
		public Assignment getChoiceAssignment_7_3() { return cChoiceAssignment_7_3; }

		//Choice
		public RuleCall getChoiceChoiceParserRuleCall_7_3_0() { return cChoiceChoiceParserRuleCall_7_3_0; }

		//("," choice+=Choice)*
		public Group getGroup_7_4() { return cGroup_7_4; }

		//","
		public Keyword getCommaKeyword_7_4_0() { return cCommaKeyword_7_4_0; }

		//choice+=Choice
		public Assignment getChoiceAssignment_7_4_1() { return cChoiceAssignment_7_4_1; }

		//Choice
		public RuleCall getChoiceChoiceParserRuleCall_7_4_1_0() { return cChoiceChoiceParserRuleCall_7_4_1_0; }

		//("or" "with"? "something"? "else"? other=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"or"
		public Keyword getOrKeyword_8_0() { return cOrKeyword_8_0; }

		//"with"?
		public Keyword getWithKeyword_8_1() { return cWithKeyword_8_1; }

		//"something"?
		public Keyword getSomethingKeyword_8_2() { return cSomethingKeyword_8_2; }

		//"else"?
		public Keyword getElseKeyword_8_3() { return cElseKeyword_8_3; }

		//other=EString
		public Assignment getOtherAssignment_8_4() { return cOtherAssignment_8_4; }

		//EString
		public RuleCall getOtherEStringParserRuleCall_8_4_0() { return cOtherEStringParserRuleCall_8_4_0; }

		//"."?
		public Keyword getFullStopKeyword_9() { return cFullStopKeyword_9; }

		//(Fork+=ChoiceFork ("," Fork+=ChoiceFork)*)?
		public Group getGroup_10() { return cGroup_10; }

		//Fork+=ChoiceFork
		public Assignment getForkAssignment_10_0() { return cForkAssignment_10_0; }

		//ChoiceFork
		public RuleCall getForkChoiceForkParserRuleCall_10_0_0() { return cForkChoiceForkParserRuleCall_10_0_0; }

		//("," Fork+=ChoiceFork)*
		public Group getGroup_10_1() { return cGroup_10_1; }

		//","
		public Keyword getCommaKeyword_10_1_0() { return cCommaKeyword_10_1_0; }

		//Fork+=ChoiceFork
		public Assignment getForkAssignment_10_1_1() { return cForkAssignment_10_1_1; }

		//ChoiceFork
		public RuleCall getForkChoiceForkParserRuleCall_10_1_1_0() { return cForkChoiceForkParserRuleCall_10_1_1_0; }
	}

	public class OpenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Open");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOpenAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOpenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTheKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cUserKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Keyword cMayKeyword_5_0 = (Keyword)cAlternatives_5.eContents().get(0);
		private final Keyword cIsRequiredKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cAnswerKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cQuestionAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cQuestionEStringParserRuleCall_6_2_0 = (RuleCall)cQuestionAssignment_6_2.eContents().get(0);
		
		//Open:
		//	{Open} "Open" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "answer"? question=EString)?;
		public ParserRule getRule() { return rule; }

		//{Open} "Open" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "answer"? question=EString)?
		public Group getGroup() { return cGroup; }

		//{Open}
		public Action getOpenAction_0() { return cOpenAction_0; }

		//"Open"
		public Keyword getOpenKeyword_1() { return cOpenKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("The"? "user")?
		public Group getGroup_4() { return cGroup_4; }

		//"The"?
		public Keyword getTheKeyword_4_0() { return cTheKeyword_4_0; }

		//"user"
		public Keyword getUserKeyword_4_1() { return cUserKeyword_4_1; }

		//("may" | "is required")?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }

		//"may"
		public Keyword getMayKeyword_5_0() { return cMayKeyword_5_0; }

		//"is required"
		public Keyword getIsRequiredKeyword_5_1() { return cIsRequiredKeyword_5_1; }

		//("to"? "answer"? question=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"to"?
		public Keyword getToKeyword_6_0() { return cToKeyword_6_0; }

		//"answer"?
		public Keyword getAnswerKeyword_6_1() { return cAnswerKeyword_6_1; }

		//question=EString
		public Assignment getQuestionAssignment_6_2() { return cQuestionAssignment_6_2; }

		//EString
		public RuleCall getQuestionEStringParserRuleCall_6_2_0() { return cQuestionEStringParserRuleCall_6_2_0; }
	}

	public class Rating_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Rating_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRatingAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRatingKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTheKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cUserKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Keyword cMayKeyword_5_0 = (Keyword)cAlternatives_5.eContents().get(0);
		private final Keyword cIsRequiredKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cRateKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cQuestionAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cQuestionEStringParserRuleCall_6_2_0 = (RuleCall)cQuestionAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cBetweenKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMinAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMinEIntParserRuleCall_7_1_0 = (RuleCall)cMinAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAndKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMaxAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMaxEIntParserRuleCall_8_1_0 = (RuleCall)cMaxAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cWhereKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLowestKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Keyword cMeansKeyword_9_2 = (Keyword)cGroup_9.eContents().get(2);
		private final Assignment cFirstAssignment_9_3 = (Assignment)cGroup_9.eContents().get(3);
		private final RuleCall cFirstEStringParserRuleCall_9_3_0 = (RuleCall)cFirstAssignment_9_3.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cAndKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cHighestKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Keyword cMeansKeyword_10_2 = (Keyword)cGroup_10.eContents().get(2);
		private final Assignment cLastAssignment_10_3 = (Assignment)cGroup_10.eContents().get(3);
		private final RuleCall cLastEStringParserRuleCall_10_3_0 = (RuleCall)cLastAssignment_10_3.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cConditionalsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cForkAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cForkRatingForkParserRuleCall_11_2_0 = (RuleCall)cForkAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cForkAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cForkRatingForkParserRuleCall_11_3_1_0 = (RuleCall)cForkAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		
		//Rating_Impl returns Rating:
		//	{Rating} "Rating" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "rate"? question=EString)? ("between"?
		//	Min=EInt)? ("and"? Max=EInt)? ("where"? "lowest"? "means"? first=EString)? ("and"? "highest"? "means"? last=EString)?
		//	("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?;
		public ParserRule getRule() { return rule; }

		//{Rating} "Rating" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "rate"? question=EString)? ("between"?
		//Min=EInt)? ("and"? Max=EInt)? ("where"? "lowest"? "means"? first=EString)? ("and"? "highest"? "means"? last=EString)?
		//("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?
		public Group getGroup() { return cGroup; }

		//{Rating}
		public Action getRatingAction_0() { return cRatingAction_0; }

		//"Rating"
		public Keyword getRatingKeyword_1() { return cRatingKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("The"? "user")?
		public Group getGroup_4() { return cGroup_4; }

		//"The"?
		public Keyword getTheKeyword_4_0() { return cTheKeyword_4_0; }

		//"user"
		public Keyword getUserKeyword_4_1() { return cUserKeyword_4_1; }

		//("may" | "is required")?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }

		//"may"
		public Keyword getMayKeyword_5_0() { return cMayKeyword_5_0; }

		//"is required"
		public Keyword getIsRequiredKeyword_5_1() { return cIsRequiredKeyword_5_1; }

		//("to"? "rate"? question=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"to"?
		public Keyword getToKeyword_6_0() { return cToKeyword_6_0; }

		//"rate"?
		public Keyword getRateKeyword_6_1() { return cRateKeyword_6_1; }

		//question=EString
		public Assignment getQuestionAssignment_6_2() { return cQuestionAssignment_6_2; }

		//EString
		public RuleCall getQuestionEStringParserRuleCall_6_2_0() { return cQuestionEStringParserRuleCall_6_2_0; }

		//("between"? Min=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"between"?
		public Keyword getBetweenKeyword_7_0() { return cBetweenKeyword_7_0; }

		//Min=EInt
		public Assignment getMinAssignment_7_1() { return cMinAssignment_7_1; }

		//EInt
		public RuleCall getMinEIntParserRuleCall_7_1_0() { return cMinEIntParserRuleCall_7_1_0; }

		//("and"? Max=EInt)?
		public Group getGroup_8() { return cGroup_8; }

		//"and"?
		public Keyword getAndKeyword_8_0() { return cAndKeyword_8_0; }

		//Max=EInt
		public Assignment getMaxAssignment_8_1() { return cMaxAssignment_8_1; }

		//EInt
		public RuleCall getMaxEIntParserRuleCall_8_1_0() { return cMaxEIntParserRuleCall_8_1_0; }

		//("where"? "lowest"? "means"? first=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"where"?
		public Keyword getWhereKeyword_9_0() { return cWhereKeyword_9_0; }

		//"lowest"?
		public Keyword getLowestKeyword_9_1() { return cLowestKeyword_9_1; }

		//"means"?
		public Keyword getMeansKeyword_9_2() { return cMeansKeyword_9_2; }

		//first=EString
		public Assignment getFirstAssignment_9_3() { return cFirstAssignment_9_3; }

		//EString
		public RuleCall getFirstEStringParserRuleCall_9_3_0() { return cFirstEStringParserRuleCall_9_3_0; }

		//("and"? "highest"? "means"? last=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"and"?
		public Keyword getAndKeyword_10_0() { return cAndKeyword_10_0; }

		//"highest"?
		public Keyword getHighestKeyword_10_1() { return cHighestKeyword_10_1; }

		//"means"?
		public Keyword getMeansKeyword_10_2() { return cMeansKeyword_10_2; }

		//last=EString
		public Assignment getLastAssignment_10_3() { return cLastAssignment_10_3; }

		//EString
		public RuleCall getLastEStringParserRuleCall_10_3_0() { return cLastEStringParserRuleCall_10_3_0; }

		//("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?
		public Group getGroup_11() { return cGroup_11; }

		//"conditionals"?
		public Keyword getConditionalsKeyword_11_0() { return cConditionalsKeyword_11_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_11_1() { return cLeftParenthesisKeyword_11_1; }

		//Fork+=RatingFork
		public Assignment getForkAssignment_11_2() { return cForkAssignment_11_2; }

		//RatingFork
		public RuleCall getForkRatingForkParserRuleCall_11_2_0() { return cForkRatingForkParserRuleCall_11_2_0; }

		//("," Fork+=RatingFork)*
		public Group getGroup_11_3() { return cGroup_11_3; }

		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }

		//Fork+=RatingFork
		public Assignment getForkAssignment_11_3_1() { return cForkAssignment_11_3_1; }

		//RatingFork
		public RuleCall getForkRatingForkParserRuleCall_11_3_1_0() { return cForkRatingForkParserRuleCall_11_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_11_4() { return cRightParenthesisKeyword_11_4; }
	}

	public class RankingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ranking");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRankingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIsRequiredKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAskKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cQuestionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cQuestionEStringParserRuleCall_4_1_0 = (RuleCall)cQuestionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cYouKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cCanKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cChooseKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Keyword cFromKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Keyword cTheseKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Assignment cChoicesAssignment_5_5 = (Assignment)cGroup_5.eContents().get(5);
		private final RuleCall cChoicesChoiceParserRuleCall_5_5_0 = (RuleCall)cChoicesAssignment_5_5.eContents().get(0);
		private final Group cGroup_5_6 = (Group)cGroup_5.eContents().get(6);
		private final Keyword cCommaKeyword_5_6_0 = (Keyword)cGroup_5_6.eContents().get(0);
		private final Assignment cChoicesAssignment_5_6_1 = (Assignment)cGroup_5_6.eContents().get(1);
		private final RuleCall cChoicesChoiceParserRuleCall_5_6_1_0 = (RuleCall)cChoicesAssignment_5_6_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cConditionalsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cForkAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cForkRankingSumForkParserRuleCall_6_2_0 = (RuleCall)cForkAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cForkAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cForkRankingSumForkParserRuleCall_6_3_1_0 = (RuleCall)cForkAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		
		//Ranking:
		//	"Ranking" name=ID ":" "is required"? ("ask"? question=EString)? ("you"? "can"? "choose" "from"? "these"?
		//	choices+=Choice ("," choices+=Choice)*)? ("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?;
		public ParserRule getRule() { return rule; }

		//"Ranking" name=ID ":" "is required"? ("ask"? question=EString)? ("you"? "can"? "choose" "from"? "these"? choices+=Choice
		//("," choices+=Choice)*)? ("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?
		public Group getGroup() { return cGroup; }

		//"Ranking"
		public Keyword getRankingKeyword_0() { return cRankingKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//"is required"?
		public Keyword getIsRequiredKeyword_3() { return cIsRequiredKeyword_3; }

		//("ask"? question=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"ask"?
		public Keyword getAskKeyword_4_0() { return cAskKeyword_4_0; }

		//question=EString
		public Assignment getQuestionAssignment_4_1() { return cQuestionAssignment_4_1; }

		//EString
		public RuleCall getQuestionEStringParserRuleCall_4_1_0() { return cQuestionEStringParserRuleCall_4_1_0; }

		//("you"? "can"? "choose" "from"? "these"? choices+=Choice ("," choices+=Choice)*)?
		public Group getGroup_5() { return cGroup_5; }

		//"you"?
		public Keyword getYouKeyword_5_0() { return cYouKeyword_5_0; }

		//"can"?
		public Keyword getCanKeyword_5_1() { return cCanKeyword_5_1; }

		//"choose"
		public Keyword getChooseKeyword_5_2() { return cChooseKeyword_5_2; }

		//"from"?
		public Keyword getFromKeyword_5_3() { return cFromKeyword_5_3; }

		//"these"?
		public Keyword getTheseKeyword_5_4() { return cTheseKeyword_5_4; }

		//choices+=Choice
		public Assignment getChoicesAssignment_5_5() { return cChoicesAssignment_5_5; }

		//Choice
		public RuleCall getChoicesChoiceParserRuleCall_5_5_0() { return cChoicesChoiceParserRuleCall_5_5_0; }

		//("," choices+=Choice)*
		public Group getGroup_5_6() { return cGroup_5_6; }

		//","
		public Keyword getCommaKeyword_5_6_0() { return cCommaKeyword_5_6_0; }

		//choices+=Choice
		public Assignment getChoicesAssignment_5_6_1() { return cChoicesAssignment_5_6_1; }

		//Choice
		public RuleCall getChoicesChoiceParserRuleCall_5_6_1_0() { return cChoicesChoiceParserRuleCall_5_6_1_0; }

		//("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?
		public Group getGroup_6() { return cGroup_6; }

		//"conditionals"?
		public Keyword getConditionalsKeyword_6_0() { return cConditionalsKeyword_6_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }

		//Fork+=RankingSumFork
		public Assignment getForkAssignment_6_2() { return cForkAssignment_6_2; }

		//RankingSumFork
		public RuleCall getForkRankingSumForkParserRuleCall_6_2_0() { return cForkRankingSumForkParserRuleCall_6_2_0; }

		//("," Fork+=RankingSumFork)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//Fork+=RankingSumFork
		public Assignment getForkAssignment_6_3_1() { return cForkAssignment_6_3_1; }

		//RankingSumFork
		public RuleCall getForkRankingSumForkParserRuleCall_6_3_1_0() { return cForkRankingSumForkParserRuleCall_6_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
	}

	public class DichotomousElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dichotomous");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDichotomousAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDichotomousKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTheKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cUserKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Keyword cMayKeyword_5_0 = (Keyword)cAlternatives_5.eContents().get(0);
		private final Keyword cIsRequiredKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cAnswerKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cQuestionAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cQuestionEStringParserRuleCall_6_2_0 = (RuleCall)cQuestionAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIfYesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cOnYesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cOnYesDichotomousForkParserRuleCall_7_1_0 = (RuleCall)cOnYesAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cIfNoKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cOnNoAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cOnNoDichotomousForkParserRuleCall_8_1_0 = (RuleCall)cOnNoAssignment_8_1.eContents().get(0);
		
		//Dichotomous:
		//	{Dichotomous} "Dichotomous" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "answer"? question=EString)?
		//	("if yes" onYes=DichotomousFork)? ("if no" onNo=DichotomousFork)?;
		public ParserRule getRule() { return rule; }

		//{Dichotomous} "Dichotomous" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "answer"? question=EString)?
		//("if yes" onYes=DichotomousFork)? ("if no" onNo=DichotomousFork)?
		public Group getGroup() { return cGroup; }

		//{Dichotomous}
		public Action getDichotomousAction_0() { return cDichotomousAction_0; }

		//"Dichotomous"
		public Keyword getDichotomousKeyword_1() { return cDichotomousKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("The"? "user")?
		public Group getGroup_4() { return cGroup_4; }

		//"The"?
		public Keyword getTheKeyword_4_0() { return cTheKeyword_4_0; }

		//"user"
		public Keyword getUserKeyword_4_1() { return cUserKeyword_4_1; }

		//("may" | "is required")?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }

		//"may"
		public Keyword getMayKeyword_5_0() { return cMayKeyword_5_0; }

		//"is required"
		public Keyword getIsRequiredKeyword_5_1() { return cIsRequiredKeyword_5_1; }

		//("to"? "answer"? question=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"to"?
		public Keyword getToKeyword_6_0() { return cToKeyword_6_0; }

		//"answer"?
		public Keyword getAnswerKeyword_6_1() { return cAnswerKeyword_6_1; }

		//question=EString
		public Assignment getQuestionAssignment_6_2() { return cQuestionAssignment_6_2; }

		//EString
		public RuleCall getQuestionEStringParserRuleCall_6_2_0() { return cQuestionEStringParserRuleCall_6_2_0; }

		//("if yes" onYes=DichotomousFork)?
		public Group getGroup_7() { return cGroup_7; }

		//"if yes"
		public Keyword getIfYesKeyword_7_0() { return cIfYesKeyword_7_0; }

		//onYes=DichotomousFork
		public Assignment getOnYesAssignment_7_1() { return cOnYesAssignment_7_1; }

		//DichotomousFork
		public RuleCall getOnYesDichotomousForkParserRuleCall_7_1_0() { return cOnYesDichotomousForkParserRuleCall_7_1_0; }

		//("if no" onNo=DichotomousFork)?
		public Group getGroup_8() { return cGroup_8; }

		//"if no"
		public Keyword getIfNoKeyword_8_0() { return cIfNoKeyword_8_0; }

		//onNo=DichotomousFork
		public Assignment getOnNoAssignment_8_1() { return cOnNoAssignment_8_1; }

		//DichotomousFork
		public RuleCall getOnNoDichotomousForkParserRuleCall_8_1_0() { return cOnNoDichotomousForkParserRuleCall_8_1_0; }
	}

	public class SumConstantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SumConstant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSumConstantAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSumConstantKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTheKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cUserKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Keyword cMayKeyword_5_0 = (Keyword)cAlternatives_5.eContents().get(0);
		private final Keyword cIsRequiredKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cDivideKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Keyword cAccordingKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Keyword cToKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Keyword cTheKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cImportanceKeyword_6_5 = (Keyword)cGroup_6.eContents().get(5);
		private final Assignment cQuestionAssignment_6_6 = (Assignment)cGroup_6.eContents().get(6);
		private final RuleCall cQuestionEStringParserRuleCall_6_6_0 = (RuleCall)cQuestionAssignment_6_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cConditionalsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cForkAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cForkRankingSumForkParserRuleCall_7_2_0 = (RuleCall)cForkAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cForkAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cForkRankingSumForkParserRuleCall_7_3_1_0 = (RuleCall)cForkAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		
		//SumConstant:
		//	{SumConstant} "SumConstant" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "divide"? "according"? "to"?
		//	"the"? "importance"? question=EString)? ("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?;
		public ParserRule getRule() { return rule; }

		//{SumConstant} "SumConstant" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "divide"? "according"? "to"?
		//"the"? "importance"? question=EString)? ("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?
		public Group getGroup() { return cGroup; }

		//{SumConstant}
		public Action getSumConstantAction_0() { return cSumConstantAction_0; }

		//"SumConstant"
		public Keyword getSumConstantKeyword_1() { return cSumConstantKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("The"? "user")?
		public Group getGroup_4() { return cGroup_4; }

		//"The"?
		public Keyword getTheKeyword_4_0() { return cTheKeyword_4_0; }

		//"user"
		public Keyword getUserKeyword_4_1() { return cUserKeyword_4_1; }

		//("may" | "is required")?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }

		//"may"
		public Keyword getMayKeyword_5_0() { return cMayKeyword_5_0; }

		//"is required"
		public Keyword getIsRequiredKeyword_5_1() { return cIsRequiredKeyword_5_1; }

		//("to"? "divide"? "according"? "to"? "the"? "importance"? question=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"to"?
		public Keyword getToKeyword_6_0() { return cToKeyword_6_0; }

		//"divide"?
		public Keyword getDivideKeyword_6_1() { return cDivideKeyword_6_1; }

		//"according"?
		public Keyword getAccordingKeyword_6_2() { return cAccordingKeyword_6_2; }

		//"to"?
		public Keyword getToKeyword_6_3() { return cToKeyword_6_3; }

		//"the"?
		public Keyword getTheKeyword_6_4() { return cTheKeyword_6_4; }

		//"importance"?
		public Keyword getImportanceKeyword_6_5() { return cImportanceKeyword_6_5; }

		//question=EString
		public Assignment getQuestionAssignment_6_6() { return cQuestionAssignment_6_6; }

		//EString
		public RuleCall getQuestionEStringParserRuleCall_6_6_0() { return cQuestionEStringParserRuleCall_6_6_0; }

		//("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?
		public Group getGroup_7() { return cGroup_7; }

		//"conditionals"?
		public Keyword getConditionalsKeyword_7_0() { return cConditionalsKeyword_7_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_7_1() { return cLeftParenthesisKeyword_7_1; }

		//Fork+=RankingSumFork
		public Assignment getForkAssignment_7_2() { return cForkAssignment_7_2; }

		//RankingSumFork
		public RuleCall getForkRankingSumForkParserRuleCall_7_2_0() { return cForkRankingSumForkParserRuleCall_7_2_0; }

		//("," Fork+=RankingSumFork)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//Fork+=RankingSumFork
		public Assignment getForkAssignment_7_3_1() { return cForkAssignment_7_3_1; }

		//RankingSumFork
		public RuleCall getForkRankingSumForkParserRuleCall_7_3_1_0() { return cForkRankingSumForkParserRuleCall_7_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_7_4() { return cRightParenthesisKeyword_7_4; }
	}

	public class StapleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Staple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStapleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStapleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTheKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cUserKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Keyword cMayKeyword_5_0 = (Keyword)cAlternatives_5.eContents().get(0);
		private final Keyword cIsRequiredKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cRateKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cQuestionAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cQuestionEStringParserRuleCall_6_2_0 = (RuleCall)cQuestionAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cBetweenKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMinAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMinEIntParserRuleCall_7_1_0 = (RuleCall)cMinAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAndKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMaxAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMaxEIntParserRuleCall_8_1_0 = (RuleCall)cMaxAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cWhereKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLowestKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Keyword cMeansKeyword_9_2 = (Keyword)cGroup_9.eContents().get(2);
		private final Keyword cCommaKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Assignment cFirstAssignment_9_4 = (Assignment)cGroup_9.eContents().get(4);
		private final RuleCall cFirstEStringParserRuleCall_9_4_0 = (RuleCall)cFirstAssignment_9_4.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cMeanKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cMeansKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cMidAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cMidEStringParserRuleCall_10_2_0 = (RuleCall)cMidAssignment_10_2.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cAndKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cHighestKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Keyword cMeansKeyword_11_2 = (Keyword)cGroup_11.eContents().get(2);
		private final Assignment cLastAssignment_11_3 = (Assignment)cGroup_11.eContents().get(3);
		private final RuleCall cLastEStringParserRuleCall_11_3_0 = (RuleCall)cLastAssignment_11_3.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cConditionalsKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cForkAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cForkRatingForkParserRuleCall_12_2_0 = (RuleCall)cForkAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cForkAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cForkRatingForkParserRuleCall_12_3_1_0 = (RuleCall)cForkAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		
		//Staple:
		//	{Staple} "Staple" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "rate"? question=EString)? ("between"?
		//	Min=EInt)? ("and"? Max=EInt)? ("where"? "lowest"? "means"? ","? first=EString)? ("mean"? "means"? mid=EString)?
		//	("and"? "highest"? "means"? last=EString)? ("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?;
		public ParserRule getRule() { return rule; }

		//{Staple} "Staple" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "rate"? question=EString)? ("between"?
		//Min=EInt)? ("and"? Max=EInt)? ("where"? "lowest"? "means"? ","? first=EString)? ("mean"? "means"? mid=EString)?
		//("and"? "highest"? "means"? last=EString)? ("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?
		public Group getGroup() { return cGroup; }

		//{Staple}
		public Action getStapleAction_0() { return cStapleAction_0; }

		//"Staple"
		public Keyword getStapleKeyword_1() { return cStapleKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("The"? "user")?
		public Group getGroup_4() { return cGroup_4; }

		//"The"?
		public Keyword getTheKeyword_4_0() { return cTheKeyword_4_0; }

		//"user"
		public Keyword getUserKeyword_4_1() { return cUserKeyword_4_1; }

		//("may" | "is required")?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }

		//"may"
		public Keyword getMayKeyword_5_0() { return cMayKeyword_5_0; }

		//"is required"
		public Keyword getIsRequiredKeyword_5_1() { return cIsRequiredKeyword_5_1; }

		//("to"? "rate"? question=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"to"?
		public Keyword getToKeyword_6_0() { return cToKeyword_6_0; }

		//"rate"?
		public Keyword getRateKeyword_6_1() { return cRateKeyword_6_1; }

		//question=EString
		public Assignment getQuestionAssignment_6_2() { return cQuestionAssignment_6_2; }

		//EString
		public RuleCall getQuestionEStringParserRuleCall_6_2_0() { return cQuestionEStringParserRuleCall_6_2_0; }

		//("between"? Min=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"between"?
		public Keyword getBetweenKeyword_7_0() { return cBetweenKeyword_7_0; }

		//Min=EInt
		public Assignment getMinAssignment_7_1() { return cMinAssignment_7_1; }

		//EInt
		public RuleCall getMinEIntParserRuleCall_7_1_0() { return cMinEIntParserRuleCall_7_1_0; }

		//("and"? Max=EInt)?
		public Group getGroup_8() { return cGroup_8; }

		//"and"?
		public Keyword getAndKeyword_8_0() { return cAndKeyword_8_0; }

		//Max=EInt
		public Assignment getMaxAssignment_8_1() { return cMaxAssignment_8_1; }

		//EInt
		public RuleCall getMaxEIntParserRuleCall_8_1_0() { return cMaxEIntParserRuleCall_8_1_0; }

		//("where"? "lowest"? "means"? ","? first=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"where"?
		public Keyword getWhereKeyword_9_0() { return cWhereKeyword_9_0; }

		//"lowest"?
		public Keyword getLowestKeyword_9_1() { return cLowestKeyword_9_1; }

		//"means"?
		public Keyword getMeansKeyword_9_2() { return cMeansKeyword_9_2; }

		//","?
		public Keyword getCommaKeyword_9_3() { return cCommaKeyword_9_3; }

		//first=EString
		public Assignment getFirstAssignment_9_4() { return cFirstAssignment_9_4; }

		//EString
		public RuleCall getFirstEStringParserRuleCall_9_4_0() { return cFirstEStringParserRuleCall_9_4_0; }

		//("mean"? "means"? mid=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"mean"?
		public Keyword getMeanKeyword_10_0() { return cMeanKeyword_10_0; }

		//"means"?
		public Keyword getMeansKeyword_10_1() { return cMeansKeyword_10_1; }

		//mid=EString
		public Assignment getMidAssignment_10_2() { return cMidAssignment_10_2; }

		//EString
		public RuleCall getMidEStringParserRuleCall_10_2_0() { return cMidEStringParserRuleCall_10_2_0; }

		//("and"? "highest"? "means"? last=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"and"?
		public Keyword getAndKeyword_11_0() { return cAndKeyword_11_0; }

		//"highest"?
		public Keyword getHighestKeyword_11_1() { return cHighestKeyword_11_1; }

		//"means"?
		public Keyword getMeansKeyword_11_2() { return cMeansKeyword_11_2; }

		//last=EString
		public Assignment getLastAssignment_11_3() { return cLastAssignment_11_3; }

		//EString
		public RuleCall getLastEStringParserRuleCall_11_3_0() { return cLastEStringParserRuleCall_11_3_0; }

		//("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?
		public Group getGroup_12() { return cGroup_12; }

		//"conditionals"?
		public Keyword getConditionalsKeyword_12_0() { return cConditionalsKeyword_12_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_12_1() { return cLeftParenthesisKeyword_12_1; }

		//Fork+=RatingFork
		public Assignment getForkAssignment_12_2() { return cForkAssignment_12_2; }

		//RatingFork
		public RuleCall getForkRatingForkParserRuleCall_12_2_0() { return cForkRatingForkParserRuleCall_12_2_0; }

		//("," Fork+=RatingFork)*
		public Group getGroup_12_3() { return cGroup_12_3; }

		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }

		//Fork+=RatingFork
		public Assignment getForkAssignment_12_3_1() { return cForkAssignment_12_3_1; }

		//RatingFork
		public RuleCall getForkRatingForkParserRuleCall_12_3_1_0() { return cForkRatingForkParserRuleCall_12_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_12_4() { return cRightParenthesisKeyword_12_4; }
	}

	public class ChoiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Choice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionEStringParserRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		
		//Choice:
		//	name=ID ":" Description=EString;
		public ParserRule getRule() { return rule; }

		//name=ID ":" Description=EString
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//Description=EString
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_2_0() { return cDescriptionEStringParserRuleCall_2_0; }
	}

	public class ChoiceForkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ChoiceFork");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cOnChoiceCrossReference_1_0 = (CrossReference)cOnAssignment_1.eContents().get(0);
		private final RuleCall cOnChoiceEStringParserRuleCall_1_0_1 = (RuleCall)cOnChoiceCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOnAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cOnChoiceCrossReference_2_1_0 = (CrossReference)cOnAssignment_2_1.eContents().get(0);
		private final RuleCall cOnChoiceEStringParserRuleCall_2_1_0_1 = (RuleCall)cOnChoiceCrossReference_2_1_0.eContents().get(1);
		private final Keyword cThenKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cGoToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cQuestionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cQuestionsQuestionCrossReference_5_0 = (CrossReference)cQuestionsAssignment_5.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_5_0_1 = (RuleCall)cQuestionsQuestionCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cQuestionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cQuestionsQuestionCrossReference_6_1_0 = (CrossReference)cQuestionsAssignment_6_1.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_6_1_0_1 = (RuleCall)cQuestionsQuestionCrossReference_6_1_0.eContents().get(1);
		
		//ChoiceFork:
		//	"If" On+=[Choice|EString] ("," On+=[Choice|EString])* "then"? "go to" Questions+=[Question|EString] (","
		//	Questions+=[Question|EString])*;
		public ParserRule getRule() { return rule; }

		//"If" On+=[Choice|EString] ("," On+=[Choice|EString])* "then"? "go to" Questions+=[Question|EString] (","
		//Questions+=[Question|EString])*
		public Group getGroup() { return cGroup; }

		//"If"
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }

		//On+=[Choice|EString]
		public Assignment getOnAssignment_1() { return cOnAssignment_1; }

		//[Choice|EString]
		public CrossReference getOnChoiceCrossReference_1_0() { return cOnChoiceCrossReference_1_0; }

		//EString
		public RuleCall getOnChoiceEStringParserRuleCall_1_0_1() { return cOnChoiceEStringParserRuleCall_1_0_1; }

		//("," On+=[Choice|EString])*
		public Group getGroup_2() { return cGroup_2; }

		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }

		//On+=[Choice|EString]
		public Assignment getOnAssignment_2_1() { return cOnAssignment_2_1; }

		//[Choice|EString]
		public CrossReference getOnChoiceCrossReference_2_1_0() { return cOnChoiceCrossReference_2_1_0; }

		//EString
		public RuleCall getOnChoiceEStringParserRuleCall_2_1_0_1() { return cOnChoiceEStringParserRuleCall_2_1_0_1; }

		//"then"?
		public Keyword getThenKeyword_3() { return cThenKeyword_3; }

		//"go to"
		public Keyword getGoToKeyword_4() { return cGoToKeyword_4; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_5() { return cQuestionsAssignment_5; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_5_0() { return cQuestionsQuestionCrossReference_5_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_5_0_1() { return cQuestionsQuestionEStringParserRuleCall_5_0_1; }

		//("," Questions+=[Question|EString])*
		public Group getGroup_6() { return cGroup_6; }

		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_6_1() { return cQuestionsAssignment_6_1; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_6_1_0() { return cQuestionsQuestionCrossReference_6_1_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_6_1_0_1() { return cQuestionsQuestionEStringParserRuleCall_6_1_0_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class RatingForkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RatingFork");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cMinKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cMinAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cMinEIntParserRuleCall_0_1_0 = (RuleCall)cMinAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cMaxKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cMaxAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMaxEIntParserRuleCall_1_1_0 = (RuleCall)cMaxAssignment_1_1.eContents().get(0);
		private final Keyword cQuestionsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cQuestionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cQuestionsQuestionCrossReference_4_0 = (CrossReference)cQuestionsAssignment_4.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_4_0_1 = (RuleCall)cQuestionsQuestionCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cQuestionsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cQuestionsQuestionCrossReference_5_1_0 = (CrossReference)cQuestionsAssignment_5_1.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_5_1_0_1 = (RuleCall)cQuestionsQuestionCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RatingFork:
		//	("Min" Min=EInt)? ("Max" Max=EInt)? "Questions" "(" Questions+=[Question|EString] (","
		//	Questions+=[Question|EString])* ")";
		public ParserRule getRule() { return rule; }

		//("Min" Min=EInt)? ("Max" Max=EInt)? "Questions" "(" Questions+=[Question|EString] ("," Questions+=[Question|EString])*
		//")"
		public Group getGroup() { return cGroup; }

		//("Min" Min=EInt)?
		public Group getGroup_0() { return cGroup_0; }

		//"Min"
		public Keyword getMinKeyword_0_0() { return cMinKeyword_0_0; }

		//Min=EInt
		public Assignment getMinAssignment_0_1() { return cMinAssignment_0_1; }

		//EInt
		public RuleCall getMinEIntParserRuleCall_0_1_0() { return cMinEIntParserRuleCall_0_1_0; }

		//("Max" Max=EInt)?
		public Group getGroup_1() { return cGroup_1; }

		//"Max"
		public Keyword getMaxKeyword_1_0() { return cMaxKeyword_1_0; }

		//Max=EInt
		public Assignment getMaxAssignment_1_1() { return cMaxAssignment_1_1; }

		//EInt
		public RuleCall getMaxEIntParserRuleCall_1_1_0() { return cMaxEIntParserRuleCall_1_1_0; }

		//"Questions"
		public Keyword getQuestionsKeyword_2() { return cQuestionsKeyword_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_4() { return cQuestionsAssignment_4; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_4_0() { return cQuestionsQuestionCrossReference_4_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_4_0_1() { return cQuestionsQuestionEStringParserRuleCall_4_0_1; }

		//("," Questions+=[Question|EString])*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_5_1() { return cQuestionsAssignment_5_1; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_5_1_0() { return cQuestionsQuestionCrossReference_5_1_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_5_1_0_1() { return cQuestionsQuestionEStringParserRuleCall_5_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}

	public class RankingSumForkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RankingSumFork");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cOnChoiceCrossReference_1_0 = (CrossReference)cOnAssignment_1.eContents().get(0);
		private final RuleCall cOnChoiceEStringParserRuleCall_1_0_1 = (RuleCall)cOnChoiceCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOnAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cOnChoiceCrossReference_2_1_0 = (CrossReference)cOnAssignment_2_1.eContents().get(0);
		private final RuleCall cOnChoiceEStringParserRuleCall_2_1_0_1 = (RuleCall)cOnChoiceCrossReference_2_1_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFromKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMaxAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMaxEIntParserRuleCall_3_1_0 = (RuleCall)cMaxAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cToKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMinAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMinEIntParserRuleCall_4_1_0 = (RuleCall)cMinAssignment_4_1.eContents().get(0);
		private final Keyword cQuestionsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cQuestionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cQuestionsQuestionCrossReference_6_0 = (CrossReference)cQuestionsAssignment_6.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_6_0_1 = (RuleCall)cQuestionsQuestionCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cQuestionsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cQuestionsQuestionCrossReference_7_1_0 = (CrossReference)cQuestionsAssignment_7_1.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_7_1_0_1 = (RuleCall)cQuestionsQuestionCrossReference_7_1_0.eContents().get(1);
		
		//RankingSumFork:
		//	"On" On+=[Choice|EString] ("," On+=[Choice|EString])* ("From" Max=EInt)? ("To" Min=EInt)? "Questions"
		//	Questions+=[Question|EString] ("," Questions+=[Question|EString])*;
		public ParserRule getRule() { return rule; }

		//"On" On+=[Choice|EString] ("," On+=[Choice|EString])* ("From" Max=EInt)? ("To" Min=EInt)? "Questions"
		//Questions+=[Question|EString] ("," Questions+=[Question|EString])*
		public Group getGroup() { return cGroup; }

		//"On"
		public Keyword getOnKeyword_0() { return cOnKeyword_0; }

		//On+=[Choice|EString]
		public Assignment getOnAssignment_1() { return cOnAssignment_1; }

		//[Choice|EString]
		public CrossReference getOnChoiceCrossReference_1_0() { return cOnChoiceCrossReference_1_0; }

		//EString
		public RuleCall getOnChoiceEStringParserRuleCall_1_0_1() { return cOnChoiceEStringParserRuleCall_1_0_1; }

		//("," On+=[Choice|EString])*
		public Group getGroup_2() { return cGroup_2; }

		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }

		//On+=[Choice|EString]
		public Assignment getOnAssignment_2_1() { return cOnAssignment_2_1; }

		//[Choice|EString]
		public CrossReference getOnChoiceCrossReference_2_1_0() { return cOnChoiceCrossReference_2_1_0; }

		//EString
		public RuleCall getOnChoiceEStringParserRuleCall_2_1_0_1() { return cOnChoiceEStringParserRuleCall_2_1_0_1; }

		//("From" Max=EInt)?
		public Group getGroup_3() { return cGroup_3; }

		//"From"
		public Keyword getFromKeyword_3_0() { return cFromKeyword_3_0; }

		//Max=EInt
		public Assignment getMaxAssignment_3_1() { return cMaxAssignment_3_1; }

		//EInt
		public RuleCall getMaxEIntParserRuleCall_3_1_0() { return cMaxEIntParserRuleCall_3_1_0; }

		//("To" Min=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"To"
		public Keyword getToKeyword_4_0() { return cToKeyword_4_0; }

		//Min=EInt
		public Assignment getMinAssignment_4_1() { return cMinAssignment_4_1; }

		//EInt
		public RuleCall getMinEIntParserRuleCall_4_1_0() { return cMinEIntParserRuleCall_4_1_0; }

		//"Questions"
		public Keyword getQuestionsKeyword_5() { return cQuestionsKeyword_5; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_6() { return cQuestionsAssignment_6; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_6_0() { return cQuestionsQuestionCrossReference_6_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_6_0_1() { return cQuestionsQuestionEStringParserRuleCall_6_0_1; }

		//("," Questions+=[Question|EString])*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_7_1() { return cQuestionsAssignment_7_1; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_7_1_0() { return cQuestionsQuestionCrossReference_7_1_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_7_1_0_1() { return cQuestionsQuestionEStringParserRuleCall_7_1_0_1; }
	}

	public class DichotomousForkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DichotomousFork");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDichotomousForkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuestionsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cQuestionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cQuestionsQuestionCrossReference_2_0 = (CrossReference)cQuestionsAssignment_2.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_2_0_1 = (RuleCall)cQuestionsQuestionCrossReference_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cQuestionsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cQuestionsQuestionCrossReference_3_1_0 = (CrossReference)cQuestionsAssignment_3_1.eContents().get(0);
		private final RuleCall cQuestionsQuestionEStringParserRuleCall_3_1_0_1 = (RuleCall)cQuestionsQuestionCrossReference_3_1_0.eContents().get(1);
		
		//DichotomousFork:
		//	"DichotomousFork" "Questions" Questions+=[Question|EString] ("," Questions+=[Question|EString])*;
		public ParserRule getRule() { return rule; }

		//"DichotomousFork" "Questions" Questions+=[Question|EString] ("," Questions+=[Question|EString])*
		public Group getGroup() { return cGroup; }

		//"DichotomousFork"
		public Keyword getDichotomousForkKeyword_0() { return cDichotomousForkKeyword_0; }

		//"Questions"
		public Keyword getQuestionsKeyword_1() { return cQuestionsKeyword_1; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_2() { return cQuestionsAssignment_2; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_2_0() { return cQuestionsQuestionCrossReference_2_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_2_0_1() { return cQuestionsQuestionEStringParserRuleCall_2_0_1; }

		//("," Questions+=[Question|EString])*
		public Group getGroup_3() { return cGroup_3; }

		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }

		//Questions+=[Question|EString]
		public Assignment getQuestionsAssignment_3_1() { return cQuestionsAssignment_3_1; }

		//[Question|EString]
		public CrossReference getQuestionsQuestionCrossReference_3_1_0() { return cQuestionsQuestionCrossReference_3_1_0; }

		//EString
		public RuleCall getQuestionsQuestionEStringParserRuleCall_3_1_0_1() { return cQuestionsQuestionEStringParserRuleCall_3_1_0_1; }
	}
	
	
	private ModelElements pModel;
	private QuestionElements pQuestion;
	private SurveyElements pSurvey;
	private EStringElements pEString;
	private EBooleanElements pEBoolean;
	private MultipleChoiceElements pMultipleChoice;
	private OpenElements pOpen;
	private Rating_ImplElements pRating_Impl;
	private RankingElements pRanking;
	private DichotomousElements pDichotomous;
	private SumConstantElements pSumConstant;
	private StapleElements pStaple;
	private ChoiceElements pChoice;
	private ChoiceForkElements pChoiceFork;
	private EIntElements pEInt;
	private RatingForkElements pRatingFork;
	private RankingSumForkElements pRankingSumFork;
	private DichotomousForkElements pDichotomousFork;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	{Model} (surveys+=Survey ("??????" surveys+=Survey)*)?;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Question:
	//	MultipleChoice | Open | Rating_Impl | Ranking | Dichotomous | SumConstant | Staple;
	public QuestionElements getQuestionAccess() {
		return (pQuestion != null) ? pQuestion : (pQuestion = new QuestionElements());
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}

	//Survey:
	//	{Survey} name=EString (questions+=Question ";" (questions+=Question ";")*)?;
	public SurveyElements getSurveyAccess() {
		return (pSurvey != null) ? pSurvey : (pSurvey = new SurveyElements());
	}
	
	public ParserRule getSurveyRule() {
		return getSurveyAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//MultipleChoice:
	//	{MultipleChoice} "MultipleChoice" name=ID ":" ("The"? "user")? ("may" | isRequired?="is required")? ("to"? "answer"?
	//	question=EString)? ("with"? ("one of" | "some of")? "these:"? choice+=Choice ("," choice+=Choice)*)? ("or" "with"?
	//	"something"? "else"? other=EString)? "."? (Fork+=ChoiceFork ("," Fork+=ChoiceFork)*)?;
	public MultipleChoiceElements getMultipleChoiceAccess() {
		return (pMultipleChoice != null) ? pMultipleChoice : (pMultipleChoice = new MultipleChoiceElements());
	}
	
	public ParserRule getMultipleChoiceRule() {
		return getMultipleChoiceAccess().getRule();
	}

	//Open:
	//	{Open} "Open" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "answer"? question=EString)?;
	public OpenElements getOpenAccess() {
		return (pOpen != null) ? pOpen : (pOpen = new OpenElements());
	}
	
	public ParserRule getOpenRule() {
		return getOpenAccess().getRule();
	}

	//Rating_Impl returns Rating:
	//	{Rating} "Rating" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "rate"? question=EString)? ("between"?
	//	Min=EInt)? ("and"? Max=EInt)? ("where"? "lowest"? "means"? first=EString)? ("and"? "highest"? "means"? last=EString)?
	//	("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?;
	public Rating_ImplElements getRating_ImplAccess() {
		return (pRating_Impl != null) ? pRating_Impl : (pRating_Impl = new Rating_ImplElements());
	}
	
	public ParserRule getRating_ImplRule() {
		return getRating_ImplAccess().getRule();
	}

	//Ranking:
	//	"Ranking" name=ID ":" "is required"? ("ask"? question=EString)? ("you"? "can"? "choose" "from"? "these"?
	//	choices+=Choice ("," choices+=Choice)*)? ("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?;
	public RankingElements getRankingAccess() {
		return (pRanking != null) ? pRanking : (pRanking = new RankingElements());
	}
	
	public ParserRule getRankingRule() {
		return getRankingAccess().getRule();
	}

	//Dichotomous:
	//	{Dichotomous} "Dichotomous" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "answer"? question=EString)?
	//	("if yes" onYes=DichotomousFork)? ("if no" onNo=DichotomousFork)?;
	public DichotomousElements getDichotomousAccess() {
		return (pDichotomous != null) ? pDichotomous : (pDichotomous = new DichotomousElements());
	}
	
	public ParserRule getDichotomousRule() {
		return getDichotomousAccess().getRule();
	}

	//SumConstant:
	//	{SumConstant} "SumConstant" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "divide"? "according"? "to"?
	//	"the"? "importance"? question=EString)? ("conditionals"? "(" Fork+=RankingSumFork ("," Fork+=RankingSumFork)* ")")?;
	public SumConstantElements getSumConstantAccess() {
		return (pSumConstant != null) ? pSumConstant : (pSumConstant = new SumConstantElements());
	}
	
	public ParserRule getSumConstantRule() {
		return getSumConstantAccess().getRule();
	}

	//Staple:
	//	{Staple} "Staple" name=ID ":" ("The"? "user")? ("may" | "is required")? ("to"? "rate"? question=EString)? ("between"?
	//	Min=EInt)? ("and"? Max=EInt)? ("where"? "lowest"? "means"? ","? first=EString)? ("mean"? "means"? mid=EString)?
	//	("and"? "highest"? "means"? last=EString)? ("conditionals"? "(" Fork+=RatingFork ("," Fork+=RatingFork)* ")")?;
	public StapleElements getStapleAccess() {
		return (pStaple != null) ? pStaple : (pStaple = new StapleElements());
	}
	
	public ParserRule getStapleRule() {
		return getStapleAccess().getRule();
	}

	//Choice:
	//	name=ID ":" Description=EString;
	public ChoiceElements getChoiceAccess() {
		return (pChoice != null) ? pChoice : (pChoice = new ChoiceElements());
	}
	
	public ParserRule getChoiceRule() {
		return getChoiceAccess().getRule();
	}

	//ChoiceFork:
	//	"If" On+=[Choice|EString] ("," On+=[Choice|EString])* "then"? "go to" Questions+=[Question|EString] (","
	//	Questions+=[Question|EString])*;
	public ChoiceForkElements getChoiceForkAccess() {
		return (pChoiceFork != null) ? pChoiceFork : (pChoiceFork = new ChoiceForkElements());
	}
	
	public ParserRule getChoiceForkRule() {
		return getChoiceForkAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//RatingFork:
	//	("Min" Min=EInt)? ("Max" Max=EInt)? "Questions" "(" Questions+=[Question|EString] (","
	//	Questions+=[Question|EString])* ")";
	public RatingForkElements getRatingForkAccess() {
		return (pRatingFork != null) ? pRatingFork : (pRatingFork = new RatingForkElements());
	}
	
	public ParserRule getRatingForkRule() {
		return getRatingForkAccess().getRule();
	}

	//RankingSumFork:
	//	"On" On+=[Choice|EString] ("," On+=[Choice|EString])* ("From" Max=EInt)? ("To" Min=EInt)? "Questions"
	//	Questions+=[Question|EString] ("," Questions+=[Question|EString])*;
	public RankingSumForkElements getRankingSumForkAccess() {
		return (pRankingSumFork != null) ? pRankingSumFork : (pRankingSumFork = new RankingSumForkElements());
	}
	
	public ParserRule getRankingSumForkRule() {
		return getRankingSumForkAccess().getRule();
	}

	//DichotomousFork:
	//	"DichotomousFork" "Questions" Questions+=[Question|EString] ("," Questions+=[Question|EString])*;
	public DichotomousForkElements getDichotomousForkAccess() {
		return (pDichotomousFork != null) ? pDichotomousFork : (pDichotomousFork = new DichotomousForkElements());
	}
	
	public ParserRule getDichotomousForkRule() {
		return getDichotomousForkAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
