/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getQuestionAccess().getAlternatives(), "rule__Question__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getMultipleChoiceAccess().getAlternatives_5(), "rule__MultipleChoice__Alternatives_5");
					put(grammarAccess.getMultipleChoiceAccess().getAlternatives_7_1(), "rule__MultipleChoice__Alternatives_7_1");
					put(grammarAccess.getOpenAccess().getAlternatives_5(), "rule__Open__Alternatives_5");
					put(grammarAccess.getRating_ImplAccess().getAlternatives_5(), "rule__Rating_Impl__Alternatives_5");
					put(grammarAccess.getDichotomousAccess().getAlternatives_5(), "rule__Dichotomous__Alternatives_5");
					put(grammarAccess.getSumConstantAccess().getAlternatives_5(), "rule__SumConstant__Alternatives_5");
					put(grammarAccess.getStapleAccess().getAlternatives_5(), "rule__Staple__Alternatives_5");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_1(), "rule__Model__Group_1__0");
					put(grammarAccess.getModelAccess().getGroup_1_1(), "rule__Model__Group_1_1__0");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getSurveyAccess().getGroup_2(), "rule__Survey__Group_2__0");
					put(grammarAccess.getSurveyAccess().getGroup_2_2(), "rule__Survey__Group_2_2__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup(), "rule__MultipleChoice__Group__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_4(), "rule__MultipleChoice__Group_4__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_6(), "rule__MultipleChoice__Group_6__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_7(), "rule__MultipleChoice__Group_7__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_7_4(), "rule__MultipleChoice__Group_7_4__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_8(), "rule__MultipleChoice__Group_8__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_10(), "rule__MultipleChoice__Group_10__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_10_1(), "rule__MultipleChoice__Group_10_1__0");
					put(grammarAccess.getOpenAccess().getGroup(), "rule__Open__Group__0");
					put(grammarAccess.getOpenAccess().getGroup_4(), "rule__Open__Group_4__0");
					put(grammarAccess.getOpenAccess().getGroup_6(), "rule__Open__Group_6__0");
					put(grammarAccess.getRating_ImplAccess().getGroup(), "rule__Rating_Impl__Group__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_4(), "rule__Rating_Impl__Group_4__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_6(), "rule__Rating_Impl__Group_6__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_7(), "rule__Rating_Impl__Group_7__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_8(), "rule__Rating_Impl__Group_8__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_9(), "rule__Rating_Impl__Group_9__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_10(), "rule__Rating_Impl__Group_10__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_11(), "rule__Rating_Impl__Group_11__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_11_3(), "rule__Rating_Impl__Group_11_3__0");
					put(grammarAccess.getRankingAccess().getGroup(), "rule__Ranking__Group__0");
					put(grammarAccess.getRankingAccess().getGroup_4(), "rule__Ranking__Group_4__0");
					put(grammarAccess.getRankingAccess().getGroup_5(), "rule__Ranking__Group_5__0");
					put(grammarAccess.getRankingAccess().getGroup_5_6(), "rule__Ranking__Group_5_6__0");
					put(grammarAccess.getRankingAccess().getGroup_6(), "rule__Ranking__Group_6__0");
					put(grammarAccess.getRankingAccess().getGroup_6_3(), "rule__Ranking__Group_6_3__0");
					put(grammarAccess.getDichotomousAccess().getGroup(), "rule__Dichotomous__Group__0");
					put(grammarAccess.getDichotomousAccess().getGroup_4(), "rule__Dichotomous__Group_4__0");
					put(grammarAccess.getDichotomousAccess().getGroup_6(), "rule__Dichotomous__Group_6__0");
					put(grammarAccess.getDichotomousAccess().getGroup_7(), "rule__Dichotomous__Group_7__0");
					put(grammarAccess.getDichotomousAccess().getGroup_8(), "rule__Dichotomous__Group_8__0");
					put(grammarAccess.getSumConstantAccess().getGroup(), "rule__SumConstant__Group__0");
					put(grammarAccess.getSumConstantAccess().getGroup_4(), "rule__SumConstant__Group_4__0");
					put(grammarAccess.getSumConstantAccess().getGroup_6(), "rule__SumConstant__Group_6__0");
					put(grammarAccess.getSumConstantAccess().getGroup_7(), "rule__SumConstant__Group_7__0");
					put(grammarAccess.getSumConstantAccess().getGroup_7_3(), "rule__SumConstant__Group_7_3__0");
					put(grammarAccess.getStapleAccess().getGroup(), "rule__Staple__Group__0");
					put(grammarAccess.getStapleAccess().getGroup_4(), "rule__Staple__Group_4__0");
					put(grammarAccess.getStapleAccess().getGroup_6(), "rule__Staple__Group_6__0");
					put(grammarAccess.getStapleAccess().getGroup_7(), "rule__Staple__Group_7__0");
					put(grammarAccess.getStapleAccess().getGroup_8(), "rule__Staple__Group_8__0");
					put(grammarAccess.getStapleAccess().getGroup_9(), "rule__Staple__Group_9__0");
					put(grammarAccess.getStapleAccess().getGroup_10(), "rule__Staple__Group_10__0");
					put(grammarAccess.getStapleAccess().getGroup_11(), "rule__Staple__Group_11__0");
					put(grammarAccess.getStapleAccess().getGroup_12(), "rule__Staple__Group_12__0");
					put(grammarAccess.getStapleAccess().getGroup_12_3(), "rule__Staple__Group_12_3__0");
					put(grammarAccess.getChoiceAccess().getGroup(), "rule__Choice__Group__0");
					put(grammarAccess.getChoiceForkAccess().getGroup(), "rule__ChoiceFork__Group__0");
					put(grammarAccess.getChoiceForkAccess().getGroup_2(), "rule__ChoiceFork__Group_2__0");
					put(grammarAccess.getChoiceForkAccess().getGroup_6(), "rule__ChoiceFork__Group_6__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getRatingForkAccess().getGroup(), "rule__RatingFork__Group__0");
					put(grammarAccess.getRatingForkAccess().getGroup_0(), "rule__RatingFork__Group_0__0");
					put(grammarAccess.getRatingForkAccess().getGroup_1(), "rule__RatingFork__Group_1__0");
					put(grammarAccess.getRatingForkAccess().getGroup_5(), "rule__RatingFork__Group_5__0");
					put(grammarAccess.getRankingSumForkAccess().getGroup(), "rule__RankingSumFork__Group__0");
					put(grammarAccess.getRankingSumForkAccess().getGroup_2(), "rule__RankingSumFork__Group_2__0");
					put(grammarAccess.getRankingSumForkAccess().getGroup_3(), "rule__RankingSumFork__Group_3__0");
					put(grammarAccess.getRankingSumForkAccess().getGroup_4(), "rule__RankingSumFork__Group_4__0");
					put(grammarAccess.getRankingSumForkAccess().getGroup_7(), "rule__RankingSumFork__Group_7__0");
					put(grammarAccess.getDichotomousForkAccess().getGroup(), "rule__DichotomousFork__Group__0");
					put(grammarAccess.getDichotomousForkAccess().getGroup_3(), "rule__DichotomousFork__Group_3__0");
					put(grammarAccess.getModelAccess().getSurveysAssignment_1_0(), "rule__Model__SurveysAssignment_1_0");
					put(grammarAccess.getModelAccess().getSurveysAssignment_1_1_1(), "rule__Model__SurveysAssignment_1_1_1");
					put(grammarAccess.getSurveyAccess().getNameAssignment_1(), "rule__Survey__NameAssignment_1");
					put(grammarAccess.getSurveyAccess().getQuestionsAssignment_2_0(), "rule__Survey__QuestionsAssignment_2_0");
					put(grammarAccess.getSurveyAccess().getQuestionsAssignment_2_2_0(), "rule__Survey__QuestionsAssignment_2_2_0");
					put(grammarAccess.getMultipleChoiceAccess().getNameAssignment_2(), "rule__MultipleChoice__NameAssignment_2");
					put(grammarAccess.getMultipleChoiceAccess().getIsRequiredAssignment_5_1(), "rule__MultipleChoice__IsRequiredAssignment_5_1");
					put(grammarAccess.getMultipleChoiceAccess().getQuestionAssignment_6_2(), "rule__MultipleChoice__QuestionAssignment_6_2");
					put(grammarAccess.getMultipleChoiceAccess().getChoiceAssignment_7_3(), "rule__MultipleChoice__ChoiceAssignment_7_3");
					put(grammarAccess.getMultipleChoiceAccess().getChoiceAssignment_7_4_1(), "rule__MultipleChoice__ChoiceAssignment_7_4_1");
					put(grammarAccess.getMultipleChoiceAccess().getOtherAssignment_8_4(), "rule__MultipleChoice__OtherAssignment_8_4");
					put(grammarAccess.getMultipleChoiceAccess().getForkAssignment_10_0(), "rule__MultipleChoice__ForkAssignment_10_0");
					put(grammarAccess.getMultipleChoiceAccess().getForkAssignment_10_1_1(), "rule__MultipleChoice__ForkAssignment_10_1_1");
					put(grammarAccess.getOpenAccess().getNameAssignment_2(), "rule__Open__NameAssignment_2");
					put(grammarAccess.getOpenAccess().getQuestionAssignment_6_2(), "rule__Open__QuestionAssignment_6_2");
					put(grammarAccess.getRating_ImplAccess().getNameAssignment_2(), "rule__Rating_Impl__NameAssignment_2");
					put(grammarAccess.getRating_ImplAccess().getQuestionAssignment_6_2(), "rule__Rating_Impl__QuestionAssignment_6_2");
					put(grammarAccess.getRating_ImplAccess().getMinAssignment_7_1(), "rule__Rating_Impl__MinAssignment_7_1");
					put(grammarAccess.getRating_ImplAccess().getMaxAssignment_8_1(), "rule__Rating_Impl__MaxAssignment_8_1");
					put(grammarAccess.getRating_ImplAccess().getFirstAssignment_9_3(), "rule__Rating_Impl__FirstAssignment_9_3");
					put(grammarAccess.getRating_ImplAccess().getLastAssignment_10_3(), "rule__Rating_Impl__LastAssignment_10_3");
					put(grammarAccess.getRating_ImplAccess().getForkAssignment_11_2(), "rule__Rating_Impl__ForkAssignment_11_2");
					put(grammarAccess.getRating_ImplAccess().getForkAssignment_11_3_1(), "rule__Rating_Impl__ForkAssignment_11_3_1");
					put(grammarAccess.getRankingAccess().getNameAssignment_1(), "rule__Ranking__NameAssignment_1");
					put(grammarAccess.getRankingAccess().getQuestionAssignment_4_1(), "rule__Ranking__QuestionAssignment_4_1");
					put(grammarAccess.getRankingAccess().getChoicesAssignment_5_5(), "rule__Ranking__ChoicesAssignment_5_5");
					put(grammarAccess.getRankingAccess().getChoicesAssignment_5_6_1(), "rule__Ranking__ChoicesAssignment_5_6_1");
					put(grammarAccess.getRankingAccess().getForkAssignment_6_2(), "rule__Ranking__ForkAssignment_6_2");
					put(grammarAccess.getRankingAccess().getForkAssignment_6_3_1(), "rule__Ranking__ForkAssignment_6_3_1");
					put(grammarAccess.getDichotomousAccess().getNameAssignment_2(), "rule__Dichotomous__NameAssignment_2");
					put(grammarAccess.getDichotomousAccess().getQuestionAssignment_6_2(), "rule__Dichotomous__QuestionAssignment_6_2");
					put(grammarAccess.getDichotomousAccess().getOnYesAssignment_7_1(), "rule__Dichotomous__OnYesAssignment_7_1");
					put(grammarAccess.getDichotomousAccess().getOnNoAssignment_8_1(), "rule__Dichotomous__OnNoAssignment_8_1");
					put(grammarAccess.getSumConstantAccess().getNameAssignment_2(), "rule__SumConstant__NameAssignment_2");
					put(grammarAccess.getSumConstantAccess().getQuestionAssignment_6_6(), "rule__SumConstant__QuestionAssignment_6_6");
					put(grammarAccess.getSumConstantAccess().getForkAssignment_7_2(), "rule__SumConstant__ForkAssignment_7_2");
					put(grammarAccess.getSumConstantAccess().getForkAssignment_7_3_1(), "rule__SumConstant__ForkAssignment_7_3_1");
					put(grammarAccess.getStapleAccess().getNameAssignment_2(), "rule__Staple__NameAssignment_2");
					put(grammarAccess.getStapleAccess().getQuestionAssignment_6_2(), "rule__Staple__QuestionAssignment_6_2");
					put(grammarAccess.getStapleAccess().getMinAssignment_7_1(), "rule__Staple__MinAssignment_7_1");
					put(grammarAccess.getStapleAccess().getMaxAssignment_8_1(), "rule__Staple__MaxAssignment_8_1");
					put(grammarAccess.getStapleAccess().getFirstAssignment_9_4(), "rule__Staple__FirstAssignment_9_4");
					put(grammarAccess.getStapleAccess().getMidAssignment_10_2(), "rule__Staple__MidAssignment_10_2");
					put(grammarAccess.getStapleAccess().getLastAssignment_11_3(), "rule__Staple__LastAssignment_11_3");
					put(grammarAccess.getStapleAccess().getForkAssignment_12_2(), "rule__Staple__ForkAssignment_12_2");
					put(grammarAccess.getStapleAccess().getForkAssignment_12_3_1(), "rule__Staple__ForkAssignment_12_3_1");
					put(grammarAccess.getChoiceAccess().getNameAssignment_0(), "rule__Choice__NameAssignment_0");
					put(grammarAccess.getChoiceAccess().getDescriptionAssignment_2(), "rule__Choice__DescriptionAssignment_2");
					put(grammarAccess.getChoiceForkAccess().getOnAssignment_1(), "rule__ChoiceFork__OnAssignment_1");
					put(grammarAccess.getChoiceForkAccess().getOnAssignment_2_1(), "rule__ChoiceFork__OnAssignment_2_1");
					put(grammarAccess.getChoiceForkAccess().getQuestionsAssignment_5(), "rule__ChoiceFork__QuestionsAssignment_5");
					put(grammarAccess.getChoiceForkAccess().getQuestionsAssignment_6_1(), "rule__ChoiceFork__QuestionsAssignment_6_1");
					put(grammarAccess.getRatingForkAccess().getMinAssignment_0_1(), "rule__RatingFork__MinAssignment_0_1");
					put(grammarAccess.getRatingForkAccess().getMaxAssignment_1_1(), "rule__RatingFork__MaxAssignment_1_1");
					put(grammarAccess.getRatingForkAccess().getQuestionsAssignment_4(), "rule__RatingFork__QuestionsAssignment_4");
					put(grammarAccess.getRatingForkAccess().getQuestionsAssignment_5_1(), "rule__RatingFork__QuestionsAssignment_5_1");
					put(grammarAccess.getRankingSumForkAccess().getOnAssignment_1(), "rule__RankingSumFork__OnAssignment_1");
					put(grammarAccess.getRankingSumForkAccess().getOnAssignment_2_1(), "rule__RankingSumFork__OnAssignment_2_1");
					put(grammarAccess.getRankingSumForkAccess().getMaxAssignment_3_1(), "rule__RankingSumFork__MaxAssignment_3_1");
					put(grammarAccess.getRankingSumForkAccess().getMinAssignment_4_1(), "rule__RankingSumFork__MinAssignment_4_1");
					put(grammarAccess.getRankingSumForkAccess().getQuestionsAssignment_6(), "rule__RankingSumFork__QuestionsAssignment_6");
					put(grammarAccess.getRankingSumForkAccess().getQuestionsAssignment_7_1(), "rule__RankingSumFork__QuestionsAssignment_7_1");
					put(grammarAccess.getDichotomousForkAccess().getQuestionsAssignment_2(), "rule__DichotomousFork__QuestionsAssignment_2");
					put(grammarAccess.getDichotomousForkAccess().getQuestionsAssignment_3_1(), "rule__DichotomousFork__QuestionsAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
